# Generated by Django 5.2.3 on 2025-08-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
