# Generated by Django 5.2.3 on 2025-08-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_mode_order_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_cost_pre_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_pre_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
