# Generated by Django 5.2.3 on 2025-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cafe_whatsapp_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
