# Generated by Django 5.2.3 on 2025-08-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_cafe_whatsapp_billing_cafe_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('KPI_REPORT', 'KPI Report'), ('BILLING', 'Billing'), ('FEEDBACK_REQUEST', 'Feedback Request'), ('OTHER', 'Other')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='cafes.cafe')),
            ],
            options={
                'indexes': [models.Index(fields=['cafe', 'sent_at'], name='cafes_messa_cafe_id_94fd26_idx')],
            },
        ),
    ]
