# Generated by Django 5.2.3 on 2025-07-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('employee', 'Employee')], max_length=10, null=True),
        ),
    ]
